apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-uat
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp-uat
    spec:
      containers:
        - name: webapp
          image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/cica/cica-repo-uat:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: CW_DCS_URL
              value: http://dcs-service-uat
            - name: CW_DCS_JWT
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_dcs_jwt
            - name: CW_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_cookie_secret
            - name: CW_GA_TRACKING_ID
              value: G-HBFPVZ3JHD
            - name: CW_URL
              value: https://uat.claim-criminal-injuries-compensation.service.justice.gov.uk
            - name: CW_LIVECHAT_CHAT_ID
              value: ff753a08-883d-453c-bf64-811301587100
            - name: CW_LIVECHAT_ALIVE
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_livechat_alive
            - name: CW_LIVECHAT_START_TIMES
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_livechat_start_times
            - name: CW_LIVECHAT_END_TIMES
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_livechat_end_times
            - name: CW_LIVECHAT_DISABLED
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_livechat_disabled
            - name: CW_LIVECHAT_MAINTENANCE_MESSAGE_ENABLED
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_livechat_maintenance_message_enabled
            - name: CW_LIVECHAT_MAINTENANCE_MESSAGE
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_livechat_maintenance_message
            - name: CW_MAINTENANCE_MESSAGE
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_maintenance_message
            - name: CW_MAINTENANCE_MESSAGE_ENABLED
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_maintenance_message_enabled
            - name: CW_OS_PLACES_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_os_places_api_key
            - name: CW_SESSION_DURATION
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: session_duration
            - name: CW_GOVUK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_govuk_client_id
            - name: CW_GOVUK_ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_govuk_issuer_url
            - name: CW_GOVUK_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_govuk_private_key
            - name: CW_INTERNAL_IP
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_internal_ip
            - name: CW_GOVUK_ACCOUNT_URL
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_govuk_account_url
  selector:
    matchLabels:
      app: webapp-uat
