apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-dev
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp-dev
    spec:
      containers:
        - name: webapp
          image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/cica/cica-repo-dev:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: CW_DCS_URL
              value: http://dcs-service-dev
            - name: CW_DCS_JWT
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_dcs_jwt
            - name: CW_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_cookie_secret
            - name: CW_GA_TRACKING_ID
              value: G-2HXYKFX8BH
            - name: CW_URL
              value: https://dev.claim-criminal-injuries-compensation.service.justice.gov.uk
            - name: CW_DOMAIN
              value: claim-criminal-injuries-compensation.service.justice.gov.uk
            - name: CW_MAINTENANCE_MESSAGE
              value: This service will be unavailable today from 3pm till 4pm due to essential maintenance. Please save your progress before this time.
            - name: CW_MAINTENANCE_MESSAGE_ENABLED
              value: 'true'
            - name: CW_OS_PLACES_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_os_places_api_key
            - name: CW_SESSION_DURATION
              valueFrom:
                secretKeyRef:
                  name: shared-secrets
                  key: session_duration
            - name: CW_GOVUK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_govuk_client_id
            - name: CW_GOVUK_ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_govuk_issuer_url
            - name: CW_GOVUK_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_govuk_private_key
            - name: CW_INTERNAL_IP
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_internal_ip
            - name: CW_GOVUK_ACCOUNT_URL
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_govuk_account_url
            - name: FEATURE_FLAGS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cica-web-secrets
                  key: cw_feature_flags_token
  selector:
    matchLabels:
      app: webapp-dev
