name: Validate Build and Deploy

on:
  push:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ministryofjustice/cica-devsecops-workflows/.github/workflows/reusable-node-ci.yml@8124dfe71b0851c4aa9fe05074c6c83c86caf6f6
    with:
      test-command: 'npx jest --ci --runInBand --bail --silent --coverage --projects jest.config.js jest.config.jsdom.js'
      lint-command: 'npx eslint .'

  security:
    permissions:
      contents: read
      security-events: write
    uses: ministryofjustice/cica-devsecops-workflows/.github/workflows/reusable-security.yml@8124dfe71b0851c4aa9fe05074c6c83c86caf6f6
    with:
      snyk-api-url: ${{ vars.SNYK_API_URL || 'https://api.snyk.io' }}
      run-snyk-monitor: ${{ github.ref == 'refs/heads/cw-deploy' }}
    secrets:
      SNYK_CLIENT_ID: ${{ secrets.SNYK_CLIENT_ID }}
      SNYK_CLIENT_SECRET: ${{ secrets.SNYK_CLIENT_SECRET }}

  container:
    needs: [ci, security]
    permissions:
      contents: read
      security-events: write
    uses: ministryofjustice/cica-devsecops-workflows/.github/workflows/reusable-container.yml@8124dfe71b0851c4aa9fe05074c6c83c86caf6f6
    with:
      image-name: cica/cica-repo-dev
      smoke-test-container-port: 3000
      snyk-api-url: ${{ vars.SNYK_API_URL || 'https://api.snyk.io' }}
    secrets:
      SNYK_CLIENT_ID: ${{ secrets.SNYK_CLIENT_ID }}
      SNYK_CLIENT_SECRET: ${{ secrets.SNYK_CLIENT_SECRET }}

  publish:
    needs: container
    if: |
      github.ref == 'refs/heads/cw-deploy' ||
      github.ref == 'refs/heads/cw-deploy-to-uat' ||
      github.ref == 'refs/heads/cw-deploy-to-staging'
    permissions:
      contents: read
      id-token: write
      attestations: write
    uses: ministryofjustice/cica-devsecops-workflows/.github/workflows/reusable-publish.yml@8124dfe71b0851c4aa9fe05074c6c83c86caf6f6
    with:
      image-name: cica/cica-repo-dev
      ecr-region: ${{ vars.ECR_REGION }}
      ecr-repository: ${{ vars.ECR_REPOSITORY }}
      run-container-monitor: ${{ github.ref == 'refs/heads/cw-deploy' }}
      snyk-api-url: ${{ vars.SNYK_API_URL || 'https://api.snyk.io' }}
    secrets:
      ECR_ROLE_TO_ASSUME: ${{ secrets.ECR_ROLE_TO_ASSUME }}
      ECR_REGISTRY_URL: ${{ secrets.ECR_REGISTRY_URL }}
      SNYK_CLIENT_ID: ${{ secrets.SNYK_CLIENT_ID }}
      SNYK_CLIENT_SECRET: ${{ secrets.SNYK_CLIENT_SECRET }}

  deploy-dev:
    needs: publish
    if: github.ref == 'refs/heads/cw-deploy'
    uses: ministryofjustice/cica-devsecops-workflows/.github/workflows/reusable-deploy-kubernetes.yml@8124dfe71b0851c4aa9fe05074c6c83c86caf6f6
    with:
      environment: dev
      namespace: claim-criminal-injuries-compensation-dev
      manifest-dir: kube_deploy/Dev
      container-name: webapp
      image-uri: ${{ needs.publish.outputs.image-uri }}
      additional-rollout-restart-deployment: custom-errors
    secrets:
      KUBE_CERT: ${{ secrets.KUBE_CERT }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}

  deploy-prod:
    needs: [publish, deploy-dev]
    if: github.ref == 'refs/heads/cw-deploy'
    uses: ministryofjustice/cica-devsecops-workflows/.github/workflows/reusable-deploy-kubernetes.yml@8124dfe71b0851c4aa9fe05074c6c83c86caf6f6
    with:
      environment: prod
      namespace: claim-criminal-injuries-compensation-prod
      manifest-dir: kube_deploy/Prod
      container-name: webapp
      image-uri: ${{ needs.publish.outputs.image-uri }}
      additional-rollout-restart-deployment: custom-errors
    secrets:
      KUBE_CERT: ${{ secrets.KUBE_CERT }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}

  deploy-uat:
    needs: publish
    if: github.ref == 'refs/heads/cw-deploy-to-uat'
    uses: ministryofjustice/cica-devsecops-workflows/.github/workflows/reusable-deploy-kubernetes.yml@8124dfe71b0851c4aa9fe05074c6c83c86caf6f6
    with:
      environment: uat
      namespace: claim-criminal-injuries-compensation-uat
      manifest-dir: kube_deploy/Uat
      container-name: webapp
      image-uri: ${{ needs.publish.outputs.image-uri }}
      additional-rollout-restart-deployment: custom-errors
    secrets:
      KUBE_CERT: ${{ secrets.KUBE_CERT }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}

  deploy-staging:
    needs: publish
    if: github.ref == 'refs/heads/cw-deploy-to-staging'
    uses: ministryofjustice/cica-devsecops-workflows/.github/workflows/reusable-deploy-kubernetes.yml@8124dfe71b0851c4aa9fe05074c6c83c86caf6f6
    with:
      environment: staging
      namespace: claim-criminal-injuries-compensation-stag
      manifest-dir: kube_deploy/Stag
      container-name: webapp
      image-uri: ${{ needs.publish.outputs.image-uri }}
      additional-rollout-restart-deployment: custom-errors
    secrets:
      KUBE_CERT: ${{ secrets.KUBE_CERT }}
      KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER }}
      KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
